apiVersion: v1
kind: Service
metadata:
  name: springboot-service
  labels:
    app: springboot-app
spec:
  type: LoadBalancer  # You can change to LoadBalancer if exposing externally
  ports:
    - port: 8080   # Port the service will expose
      targetPort: 8080   # Port on which your Spring Boot app is running
  selector:
    app: springboot-app
